-- Strict SQL mode disabled:
SET sql_mode = '';

INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('1','1','Renault ZOE R135','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('2','1','Renault ZOE R110','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('3','2','Renault ZOE R110','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('4','2','Renault ZOE R75','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('5','2','Renault ZOE R90','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('6','3','Renault ZOE Q90','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('7','4','Renault ZOE R240','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('8','5','Renault ZOE R210/Q210','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('9','5','Renault ZOE Q90','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('10','6','Tesla Model 3 Autonomie Standard Plus','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('11','7','Tesla Model 3 Grande autonomie','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('12','8','Tesla Model 3 Performance','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('13','9','Peugeot e-208','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('14','10','Volkswagen ID3 Pure','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('15','11','Volkswagen ID3 Pro Performance','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('16','12','Volkswagen ID3 Pro S','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('17','13','Tesla Model S Autonomie Standard','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('18','14','Tesla Model S Grande autonomie','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('19','15','Tesla Model S Performance','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('20','16','Tesla Model S 70','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('21','17','Tesla Model S 70D','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('22','18','Tesla Model S Plaid','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('23','19','BMW i3 120 Ah','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('24','20','BMW i3 94 Ah','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('25','21','BMW i3 94 Ah REX','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('26','22','BMW i3 60 Ah','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('27','22','BMW i3 60 Ah REX','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('28','23','Renault Twizy 45','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('29','24','Renault Twizy 80','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('30','25','Kia e-Niro 64','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('31','26','Kia e-Niro 39','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('32','27','Citroën Ami','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('33','28','Tesla Model Y Grande Autonomie','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('34','29','Tesla Model Y Performance','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('35','30','Porsche Taycan Turbo','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('36','31','Porsche Taycan Turbo S','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('37','32','Porsche Taycan 4S','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('38','33','Porsche Taycan 4S Plus','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('39','34','Hyundai Kona électrique 64','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('40','26','Hyundai Kona électrique 39','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('41','35','Audi e-tron S','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('42','36','Audi e-tron 50 Quattro','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('43','37','Audi e-tron 55 Quattro','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('44','36','Tesla Model X Plaid','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('45','37','Tesla Model X Autonomie Standard','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('46','39','Tesla Model X Grande Autonomie','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('47','40','Tesla Model X Performance','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('48','41','Honda e Base','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('49','42','Honda e Advance','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('50','43','Mercedes EQC 400 4MATIC','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('51','44','Renault Twingo électrique','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('52','45','DS 3 Crossback E-tense','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('53','46','Nissan Leaf 62','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('54','47','Nissan Leaf 40','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('55','48','Peugeot e-2008','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('56','49','Mini Cooper SE','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('58','50','Opel Corsa électrique','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('59','51','Ford Mustang Mach-E RWD 76','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('60','52','Ford Mustang Mach-E RWD 99','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('61','53','Ford Mustang Mach-E AWD 76','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('62','54','Ford Mustang Mach-E AWD 99','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('63','55','Ford Mustang Mach-E GT','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('64','56','Smart Fortwo Electric Drive/EQ 81','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('65','57','Smart Fortwo Electric Drive/EQ 75','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('66','58','Peugeot iOn','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('67','59','Renault Kangoo électrique','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('68','60','Volkswagen e-UP 36','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('69','61','Volkswagen e-UP 18','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('70','62','Hyundai Ioniq électrique 38','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('71','63','Hyundai Ioniq électrique 28','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('72','64','Citroën e-Méhari','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('73','65','Skoda Citigo électrique','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('74','66','Jaguar I-Pace EV400','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('75','67','Jaguar I-Pace EV320','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('76','68','Volkswagen ID4 Pro Performance','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('77','69','Volkswagen ID4 Pure Performance','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('78','69','Volkswagen ID4 Pure','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('79','70','Audi e-tron Sportback 55 quattro','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('80','71','Audi e-tron Sportback 50 quattro','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('81','72','Audi e-tron Sportback S','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('82','73','MG ZS EV','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('84','77','Citroën C-ZERO','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('85','78','BMW iX3','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('86','79','Skoda Enyaq 83','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('87','80','Skoda Enyaq iV 50','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('88','81','Skoda Enyaq iV 60','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('89','82','Skoda Enyaq iV 80','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('90','83','Skoda Enyaq iV 80 4x4','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('91','83','Skoda Enyaq RS iV 80','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('92','84','Nissan e-NV200 40','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('93','85','Nissan e-NV200 24','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('94','86','Citroën ë-C4 électrique','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('95','87','Bolloré Bluesummer','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('96','88','Peugeot Partner Electric','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('97','89','Volvo XC40 électrique','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('98','90','Seat Mii électrique','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('99','91','BMW i3s 94Ah','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('100','92','BMW i3s 94Ah REX','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('101','93','BMW i3s 120 Ah','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('102','94','Smart Forfour Electric Drive/EQ','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('103','95','Mazda MX-30','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('104','96','Opel Mokka-e','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('105','97','Renault Master ZE','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('106','98','Lexus UX 300e','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('107','99','Fiat 500e électrique 24','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('108','100','Fiat 500e électrique 42','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('109','101','Fiat 500e électrique 23','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('110','102','Mitsubishi i-MiEV','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('111','103','Kia e-Soul 64','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('112','104','Kia e-Soul 39','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('113','105','Peugeot Partner Tepee électrique','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('114','106','Nissan e-NV200 Evalia 38','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('115','107','Nissan e-NV200 Evalia 24','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('116','108','Volkswagen e-Crafter','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('117','109','Citroën e-Berlingo Multispace','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('118','110','Mercedes eVito','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('119','111','Citroën ë-SpaceTourer 50','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('120','112','Citroën ë-SpaceTourer 75','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('121','113','Mercedes eSprinter 41','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('122','114','Mercedes eSprinter 55','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('123','115','Opel Zafira-e Life 50','100');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele, Chargement) VALUES ('124','116','Opel Zafira-e Life 75','100');
