
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('1','1','Renault ZOE R135');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('2','1','Renault ZOE R110');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('3','2','Renault ZOE R110');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('4','2','Renault ZOE R75');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('5','2','Renault ZOE R90');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('6','3','Renault ZOE Q90');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('7','4','Renault ZOE R240');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('8','5','Renault ZOE R210/Q210');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('9','5','Renault ZOE Q90');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('9','6','Tesla Model 3 Autonomie Standard Plus');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('10','7','Tesla Model 3 Grande autonomie');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('11','8','Tesla Model 3 Performance');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('12','9','Peugeot e-208');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('13','10','Volkswagen ID3 Pure');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('14','11','Volkswagen ID3 Pro Performance');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('15','12','Volkswagen ID3 Pro S');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('16','13','Tesla Model S Autonomie Standard');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('17','14','Tesla Model S Grande autonomie');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('18','15','Tesla Model S Performance');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('19','16','Tesla Model S 70');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('20','17','Tesla Model S 70D');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('20','18','Tesla Model S Plaid');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('21','19','BMW i3 120 Ah');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('22','20','BMW i3 94 Ah');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('23','21','BMW i3 94 Ah REX');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('24','22','BMW i3 60 Ah');
INSERT INTO BorneToGo.Voiture (idVoiture, idBatterie, Modele) VALUES ('25','22','BMW i3 60 Ah REX');