# Derived from official mysql image (our base image)
FROM mysql:8.0

EXPOSE 3306


# COPY ./fill.sh ./var/lib/mysql
# COPY ./bigScript.sql ./var/lib/mysql

# VOLUME .data/ /var/lib/mysql/

# RUN sh ./fill.sh

# Working directory for the following instructions (?):
# WORKDIR /docker-entrypoint-initdb.d/

# Create a directory:
# RUN mkdir /usr/sql
# RUN chmod 644 /usr/sql
